
def throwError(msg):
    print(msg)
    exit()